export const CREATE_BOOKING_FAIL= "CREATE_BOOKING_FAIL"
export const CREATE_BOOKING_SUCCESS = "CREATE_BOOKING_SUCCESS"
export const GET_BOOKINGS_SUCCESS = "GET_BOOKING_SUCCESS"
export const GET_BOOKINGS_FAIL = "GET_BOOKING_FAIL"

export const BOOKING_DATA_SAVED = "BOOKING_DATA_SAVED"
export const CONFIRM_BOOKING_SUCCESS = "CONFIRM_BOOKING_SUCCESS"
export const CONFIRM_BOOKING_FAIL = "CONFIRM_BOOKING_FAIL"