export const SEARCH_PARKINGS_SUCCESS = "SEARCH_PARKINGS_SUCCESS";
export const SEARCH_PARKINGS_FAIL = "SEARCH_PARKINGS_FAIL";
export const GET_PARKING_BY_ID = "GET_PARKING_BY_ID";
export const SELECTED_PARKING_SAVED = "SELECTED_PARKING_SAVED"
export const GET_SELECTED_PARKING = "GET_SELECTED_PARKING"

export const GET_PARTICULAR_PARKING_SUCCESS = "GET_PARTICULAR_PARKING_SUCCESS"
export const GET_PARTICULAR_PARKING_FAIL = "GET_PARTICULAR_PARKING_FAIL"